
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Mon Jan 26 11:19:14 CET 2004
//----------------------------------------------------

package es.upm.fi.dia.ontology.webode.Axiom;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EXHAUSTIVE = 5;
  public static final int IMPLICA = 16;
  public static final int AND = 14;
  public static final int MULTIPLICACION = 26;
  public static final int MENOR = 22;
  public static final int FORALL = 8;
  public static final int MENORIGUAL = 20;
  public static final int IGUAL = 19;
  public static final int OR = 13;
  public static final int DIVISION = 27;
  public static final int SUMA = 24;
  public static final int NOT = 15;
  public static final int PARENABIERTO = 12;
  public static final int NUMEROREAL = 28;
  public static final int DISJOINT = 4;
  public static final int SUBCLASS = 2;
  public static final int NOT_SUBCLASS = 3;
  public static final int COMA = 10;
  public static final int TRANSITIVE = 6;
  public static final int MAYOR = 23;
  public static final int EOF = 0;
  public static final int PARENCERRADO = 11;
  public static final int MAYORIGUAL = 21;
  public static final int INSTRANSITIVE = 7;
  public static final int error = 1;
  public static final int EXISTS = 9;
  public static final int IDENTIFICADOR = 18;
  public static final int DOBLEIMPLICA = 17;
  public static final int NUMEROENTERO = 29;
  public static final int RESTA = 25;
}

