
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Mon Jan 26 11:16:19 CET 2004
//----------------------------------------------------

package es.upm.fi.dia.ontology.webode.Axiom;

/** CUP generated class containing symbol constants. */
public class symRule {
  /* terminals */
  public static final int EXHAUSTIVE = 5;
  public static final int AND = 11;
  public static final int MULTIPLICACION = 22;
  public static final int MENOR = 18;
  public static final int IGUAL = 15;
  public static final int MENORIGUAL = 16;
  public static final int THEN = 13;
  public static final int DIVISION = 23;
  public static final int SUMA = 20;
  public static final int PARENABIERTO = 10;
  public static final int NUMEROREAL = 24;
  public static final int IF = 12;
  public static final int DISJOINT = 4;
  public static final int SUBCLASS = 2;
  public static final int NOT_SUBCLASS = 3;
  public static final int COMA = 8;
  public static final int TRANSITIVE = 6;
  public static final int MAYOR = 19;
  public static final int EOF = 0;
  public static final int PARENCERRADO = 9;
  public static final int MAYORIGUAL = 17;
  public static final int INSTRANSITIVE = 7;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 14;
  public static final int NUMEROENTERO = 25;
  public static final int RESTA = 21;
}

